# Generated by Django 5.1.2 on 2024-10-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'petrol'), ('CNG', 'CNG'), ('EV', 'EV'), ('diesel', 'diesel')], default='petrol', max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner_type',
            field=models.CharField(choices=[('single', 'single'), ('second', 'second'), ('other', 'other')], default='single', max_length=200),
        ),
    ]
