# Generated by Django 5.1.2 on 2024-10-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_vehicle_fuel_type_alter_vehicle_owner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='picture',
            field=models.ImageField(null=True, upload_to='vehicle_image'),
        ),
    ]
